plugins {
    id 'com.ldtteam.tableau.maven-publishing' version '0.0.80'
    id 'com.communi-suggestu.obumbratio' version '0.0.14'
}

platform {
    fabric {
        loaderVersion = rootProject.property('fabric.loader.version')
        apiVersion = rootProject.property('fabric.api.version')
        accessWideners = rootProject.file("common/scena.accesswidener")
    }
}

tableau {
    project {
        group = "com.communi-suggestu.scena"
        publisher = "communi-suggestu"
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
    maven {
        publishToLDTTeamMaven('communi-suggestu-scena')
        publishLocally()
        pom({
            usingMitLicense()
            usingGit()
        })
    }
}

shaders {
    enable()
    sodium()
    fabric()
}

dependencies {
    modImplementation "com.communi-suggestu.saecularia-caudices:fabric:${project.property('communi.suggestu.saecularia.caudices.version')}"
    include "com.communi-suggestu.saecularia-caudices:fabric:${project.property('communi.suggestu.saecularia.caudices.version')}"
}

tasks.withType(Jar.class).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}