plugins {
    id 'com.ldtteam.tableau.common' version '0.0.62'
}

tableau {
    project {
        group = "com.communi-suggestu.scena"
        publisher = "communi-suggestu"
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
}

allprojects {Project project ->
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(project.getProperties().get("java.version")))
        }
    }
}