plugins {
    id 'com.ldtteam.tableau.common' version '0.0.62'
}

tableau {
    project {
        group = "com.communi-suggestu.scena"
        publisher = "communi-suggestu"
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
}

allprojects {Project project ->
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(project.getProperties().get("java.version")))
        }
    }

    repositories {
        maven {
            name 'Maven for PR #1874' // https://github.com/neoforged/NeoForge/pull/1874
            url 'https://prmaven.neoforged.net/NeoForge/pr1874'
            content {
                includeModule('net.neoforged', 'testframework')
                includeModule('net.neoforged', 'neoforge')
            }
        }
    }
}