### Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.debug=false

### Toolchain setup
java.version=21

### Project
type=MOD
license=MIT
author=communi-suggestu
description=Cross-Platform Minecraft Modding System
modId=scena

### Minecraft
minecraft.version=1.21.9
minecraft.additionalVersions=

### Parchment
parchment.version=2025.07.20
parchment.minecraftVersion=1.21.8

### Neoforge
neoforge.version=21.9.+
neoforge.data.runs=clientData

### Fabric
fabric.loader.version=0.+
fabric.api.version=0.133.11

### Versioning
local.version=1.21.9-local

### Dependency versioning
jetbrains.annotations.version=+
communi.suggestu.saecularia.caudices.version=[21.9,)

# Compatibility layers
compat.shaders.enabled=false
compat.shaders.versions.sodium.version=0.6.5
compat.shaders.versions.sodium.fabric.api=0.4.42+d1308ded19
compat.shaders.versions.sodium.fabric.renderer=3.4.0+acb05a3919
compat.shaders.versions.iris.version=1.8.1
compat.shaders.versions.iris.antlr4.runtime=4.13.1
compat.shaders.versions.iris.glsl.transformer=2.0.1
compat.shaders.versions.iris.jcpp=1.4.14
compat.shaders.versions.embeddium=1.0.15
compat.shaders.versions.monocle=0.1.8