### Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.debug=false

### Toolchain setup
javaVersion=21

### Versioning
localVersion=1.0.100-LOCAL
projectOwner=Communi-Suggestu
description=Cross-Platform Minecraft Modding System
modId=scena


### Dependency versioning
minecraftVersion=1.20.6
additionalMinecraftVersions=1.20.5
parchmentVersion=2024.05.01
parchmentMinecraftVersion=1.20.6
jetbrainsAnnotationsVersion=23.0.0
fabricLoaderVersion=0.15.10
fabricVersion=0.97.8
forgeVersion=20.6.30-beta
saeculariaCaudicesVersion=1.0.40

# Metadata
author=OrionDevelopment

# Maven data
githubUrl=https://github.com/Communi-Suggestu/Scena
gitUrl=https://github.com/Communi-Suggestu/Scena.git
gitConnectUrl=https://github.com/Communi-Suggestu/Scena.git
projectUrl=https://github.com/Communi-Suggestu/Scena
