pluginManagement {
    repositories {
        mavenLocal()
        maven {
            url 'https://ldtteam.jfrog.io/artifactory/communi-suggestu-maven'
            name 'Communi-Suggestu Maven'
        }
        maven {
            url 'https://ldtteam.jfrog.io/artifactory/tableau'
            name 'Tableau Maven'
        }
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
    id 'com.communi-suggestu.placitum' version '0.0.73'
}

rootProject.name = "scena"

platforms {
    core(':core')
    modernFabric(':fabric')
    neoforge(':neoforge')

    defaults {
        java {
            version = 25
        }
        project {
            owner = "communi-suggestu"
        }
    }
}