plugins {
    alias(libs.plugins.tableau.maven.publishing)
}


platform {
    minecraft {
        version = "1.21.11-pre2-20251124.022710"
    }
    project {
        library()
        accessTransformers.from(rootProject.files('common/accesstransformer.cfg'))
    }
}


tableau {
    project {
        group = "com.communi-suggestu.scena"
        publisher = "communi-suggestu"
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
    maven {
        publishToLDTTeamMaven('communi-suggestu-scena')
        publishLocally()
        pom({
            usingMitLicense()
            usingGit()
        })
    }
}

dependencies {
    api "com.communi-suggestu.saecularia-caudices:core:${project.property('communi.suggestu.saecularia.caudices.version')}"
}