modLoader="javafml"
loaderVersion="[1,)"
license="GLGPLv3"

[[mods]] #mandatory
modId="@id@"
version="@version@"
displayName="@name@"
authors="@author@"
logoFile="logo-forge.png"
description='''
@description@
'''
[[dependencies.@id@]]
    modId="neoforge" #mandatory
    required=true #mandatory
    versionRange="[@forgeVersion@,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.@id@]]
    modId="minecraft" #mandatory
    required=true #mandatory
    versionRange="[@minecraftVersion@]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.@id@]]
    modId="saeculariacaudices"
    required=true
    versionRange="@supportedSaeculariaCaudicesVersionRange@"
    ordering="AFTER"
    side="BOTH"
[[mixins]]
config="scena.mixins.json"
