plugins {
    alias(libs.plugins.tableau.maven.publishing)
    alias(libs.plugins.obumbratio)
}

repositories {
    maven {
        name = "Maven for PR #2815" // https://github.com/neoforged/NeoForge/pull/2815
        url = uri("https://prmaven.neoforged.net/NeoForge/pr2815")
        content {
            includeModule("net.neoforged", "neoforge")
            includeModule("net.neoforged", "testframework")
        }
    }
}

platform {
    neoforge {
        accessTransformers.from(rootProject.files("common/forge.accesstransformer.cfg"))
    }
}

tableau {
    project {
        group = "com.communi-suggestu.scena"
        publisher = "communi-suggestu"
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
    maven {
        publishToLDTTeamMaven('communi-suggestu-scena')
        publishLocally()
        pom({
            usingMitLicense()
            usingGit()
        })
    }
}

/*
shaders {
    enable()
    sodium()
    embeddium()
    neoforge()
}
*/

dependencies {
    includedLibraries "com.communi-suggestu.saecularia-caudices:neoforge:${project.property('communi.suggestu.saecularia.caudices.version')}"
}
